version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5433:5432" # Host port : Container port
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
